name: "Reviewer lottery"
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v1
      - uses: uesteibar/reviewer-lottery@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
